/* Generated by Yosys 0.36+3 (git sha1 a53032104, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

module fault(a, b, c, d, x);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  output x;
  wire x;
  assign x = 32'd3490512896 >> { 1'h1, a, b, d, c };
endmodule
